/* Generated By:JavaCC: Do not edit this line. ScannerConstants.java */
package yapl.impl.scanner;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ScannerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letter = 5;
  /** RegularExpression Id. */
  int digit = 6;
  /** RegularExpression Id. */
  int otherchar = 7;
  /** RegularExpression Id. */
  int ident = 8;
  /** RegularExpression Id. */
  int number = 9;
  /** RegularExpression Id. */
  int string = 10;
  /** RegularExpression Id. */
  int comment = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<letter>",
    "<digit>",
    "<otherchar>",
    "<ident>",
    "<number>",
    "<string>",
    "<comment>",
  };

}
