/* Generated By:JavaCC: Do not edit this line. SimpleGrammarConstants.java */
package yapl.impl.simpleGrammar;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int a = 5;
  /** RegularExpression Id. */
  int b = 6;
  /** RegularExpression Id. */
  int c = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"a\"",
    "\"b\"",
    "\"c\"",
  };

}
